import { render } from 'react-dom'
import React, { useRef } from 'react'
import clamp from 'lodash-es/clamp'
import { useSprings, animated, useSpring } from 'react-spring'
import { useGesture } from 'react-use-gesture'
import './styles.css'
import { delay } from 'lodash-es'

const pages = [
  'https://i.ibb.co/zh3Ny54/AIC.jpg',
  'https://i.ibb.co/bFxFmWL/Accuracy.jpg',
  'https://i.ibb.co/ts7TPQp/AdaBoost.png',
  'https://i.ibb.co/HH9k6TC/Adjusted-R-Squared.png',
  'https://i.ibb.co/v3PCGns/Aggomerative-Clustering.png',
  'https://i.ibb.co/xfxmQkz/Alpha-In-Ridge-Regression.png',
  'https://i.ibb.co/4MJLmcb/Avoid-Overfitting.jpg',
  'https://i.ibb.co/YdF8cfg/Backward-Stepwise-Selection.jpg',
  'https://i.ibb.co/WFZ9jdg/Bagging.jpg',
  'https://i.ibb.co/7QJqQxk/Basic-Parts-Of-Deep-Learning.png',
  'https://i.ibb.co/VHLkpJV/Bayes-Theorem.jpg',
  'https://i.ibb.co/KKwbF3t/Bias-Variance-Tradeoff.png',
  'https://i.ibb.co/kBzV3zB/Big-O.jpg',
  'https://i.ibb.co/hVdWRxZ/Bootstrap.jpg',
  'https://i.ibb.co/dkYFpxx/Brier-Score.jpg',
  'https://i.ibb.co/hB8L9Vb/C.png',
  'https://i.ibb.co/2sJsttC/CP.jpg',
  'https://i.ibb.co/CWc1fDG/Calculating-VIF.jpg',
  'https://i.ibb.co/Kz6QDFG/Chi-Squared-for-Feature-Selection.jpg',
  'https://i.ibb.co/mXCM8HP/Chi-Squared.png',
  'https://i.ibb.co/vBKXb6M/Coefficient-of-Determination-R2.jpg',
  'https://i.ibb.co/5h4wBZR/Common-Mathematical-Notation.jpg',
  'https://i.ibb.co/rFHTjDM/Common-Optimizers-With-Neural-Networks.png',
  'https://i.ibb.co/qrnBHYw/Common-Output-Layer-Activation-Functions.png',
  'https://i.ibb.co/fFFrJSh/Concave-And-Convex-Functions.png',
  'https://i.ibb.co/8rdxkQ3/Conditional-Probability.png',
  'https://i.ibb.co/pZxMh1v/Conditioning.png',
  'https://i.ibb.co/pRX0sQX/Confusion-Matrix.jpg',
  'https://i.ibb.co/KbkDkZr/Confusion-Matrix2.jpg',
  'https://i.ibb.co/YN7f4R3/Convex-Hulls-with-SVMs.jpg',
  'https://i.ibb.co/Rz9t6kK/Correlation-of-Error-Terms.jpg',
  'https://i.ibb.co/ScqxFCx/Correlation.jpg',
  'https://i.ibb.co/x6b7Vjy/Cost-Loss-And-Error-Functions.jpg',
  'https://i.ibb.co/8sm3Wzp/Cost-Loss-Error-Function.jpg',
  'https://i.ibb.co/CQZxnkQ/Covariance-and-Correlation.jpg',
  'https://i.ibb.co/r3mTdVd/Cross-Entropy.jpg',
  'https://i.ibb.co/PxMzRPW/Cumulative-Distribution-Function.jpg',
  'https://i.ibb.co/zSTdsgs/Current-status.png',
  'https://i.ibb.co/Hh3PFk9/Curse-Of-Dimensionality.png',
  'https://i.ibb.co/CVVZMNC/Data-Generating-Distribution.png',
  'https://i.ibb.co/R23JSDF/Dataset-Augmentation.png',
  'https://i.ibb.co/2vqNHsG/Decision-Boundary.jpg',
  'https://i.ibb.co/mzyNYGq/Decision-Tree-Regression.png',
  'https://i.ibb.co/BLmbbwL/Downsampling.png',
  'https://i.ibb.co/4NV68Qk/ELUs.png',
  'https://i.ibb.co/3pKTwjc/Effect-Of-Feature-Scaling-On-Gradient-Descent.jpg',
  'https://i.ibb.co/FJBWmgF/Effect-of-K-039-s-Value-in-KNN.jpg',
  'https://i.ibb.co/gzBF9M4/Eigenvector.png',
  'https://i.ibb.co/dLm88pN/Elastic-Net.png',
  'https://i.ibb.co/vxwBMSH/Error-Types.jpg',
  'https://i.ibb.co/HYx88GP/Euclidean-Distance.jpg',
  'https://i.ibb.co/PGYvXx6/Euclidean-Norm.jpg',
  'https://i.ibb.co/wJxry2t/Explained-Sum-Of-Squares.jpg',
  'https://i.ibb.co/YD1jyph/Exploding-Gradient-Problem.png',
  'https://i.ibb.co/gm97NPr/F-Statistic.png',
  'https://i.ibb.co/566597Q/F1-Score.jpg',
  'https://i.ibb.co/sWnMX2T/F1-Score.jpg',
  'https://i.ibb.co/phJB7ML/False-Positive-Rate.png',
  'https://i.ibb.co/sjkkDSQ/Feature-Selection-Strategies.jpg',
  'https://i.ibb.co/FBt9xDb/Finding-Linear-Regression-Parameters.png',
  'https://i.ibb.co/1fs7mck/Fowlkes-Mallows-Score.jpg',
  'https://i.ibb.co/ch70gKB/Fowlkes-Mallows.png',
  'https://i.ibb.co/cT1NZF0/Fundamental-Theorem-of-Calculus.jpg',
  'https://i.ibb.co/vH7VL3P/General-Additive-Model.jpg',
  'https://i.ibb.co/4f0GjdQ/Gini-Index.jpg',
  'https://i.ibb.co/CwZgw4k/Gradient-Descent.png',
  'https://i.ibb.co/bWBXCqt/Greek-Letters-1.png',
  ' https://i.ibb.co/Qm2pv5X/Greek-Letters-3.png',
  ' https://i.ibb.co/2spQ31H/Hamming-Loss.jpg',
  ' https://i.ibb.co/hX2xx2W/Handling-Imbalanced-Classes-In-Support-Vector-Machines.png',
  ' https://i.ibb.co/W5jgqLX/Handling-Outliers.jpg',
  ' https://i.ibb.co/YBr4C65/Hessian-Matrix.png',
  ' https://i.ibb.co/hBfHLMP/Heteroskedasticity.jpg',
  ' https://i.ibb.co/fdbLtGF/Hidden-Layer.png',
  ' https://i.ibb.co/5hKSbfH/Hinge-Loss.jpg',
  ' https://i.ibb.co/8df9Szg/How-Norm-Penalties-Work.png',
  ' https://i.ibb.co/2hh84j0/How-to-avoid-overfitting.jpg',
  ' https://i.ibb.co/qNWMQKD/Hyperplane.png',
  ' https://i.ibb.co/xgPc6DJ/Imputation-Using-k-NN.png',
  ' https://i.ibb.co/PCZFcFm/Imputation-Using-k-NN.jpg',
  ' https://i.ibb.co/JRgZfyD/Imputing-Missing-Values.png',
  ' https://i.ibb.co/2hcxywL/Initializing-Weights-In-Feedforward-Neural-Networks.png',
  ' https://i.ibb.co/9gwDzkp/Interaction-Term.png',
  ' https://i.ibb.co/1LjW2Hv/Interpolation.jpg',
  ' https://i.ibb.co/QjTNxf0/Jacobian-Matrix.png',
  ' https://i.ibb.co/PNP6qgb/K-Nearest-Neighbors-Tips-And-Tricks.png',
  ' https://i.ibb.co/7218XCr/KNN.jpg',
  ' https://i.ibb.co/HpsQhQy/Kernel-PCA.png',
  ' https://i.ibb.co/gdYzsyd/Kernel-Trick.png',
  ' https://i.ibb.co/TbkPmpb/L1-Norm.jpg',
  ' https://i.ibb.co/SXLzLF5/LDA-for-Dimensionality-Reduction.jpg',
  ' https://i.ibb.co/tbK086N/Lazy-KNN.jpg',
  ' https://i.ibb.co/tQqbJL8/Learning-Curve.png',
  ' https://i.ibb.co/Sxh61V7/Leave-One-Out-Cross-Validation.jpg',
  ' https://i.ibb.co/w7NzmJm/Linear-Combination.png',
  ' https://i.ibb.co/mRBg7Nq/Linear-Discriminant-Analysis.jpg',
  ' https://i.ibb.co/4f0GjdQ/Gini-Index.jpg',
  ' https://i.ibb.co/CwZgw4k/Gradient-Descent.png',
  ' https://i.ibb.co/bWBXCqt/Greek-Letters-1.png',
  ' https://i.ibb.co/Qm2pv5X/Greek-Letters-3.png',
  ' https://i.ibb.co/2spQ31H/Hamming-Loss.jpg',
  ' https://i.ibb.co/hX2xx2W/Handling-Imbalanced-Classes-In-Support-Vector-Machines.png',
  ' https://i.ibb.co/W5jgqLX/Handling-Outliers.jpg',
  ' https://i.ibb.co/YBr4C65/Hessian-Matrix.png',
  ' https://i.ibb.co/hBfHLMP/Heteroskedasticity.jpg',
  ' https://i.ibb.co/fdbLtGF/Hidden-Layer.png',
  ' https://i.ibb.co/5hKSbfH/Hinge-Loss.jpg',
  ' https://i.ibb.co/8df9Szg/How-Norm-Penalties-Work.png',
  ' https://i.ibb.co/2hh84j0/How-to-avoid-overfitting.jpg',
  ' https://i.ibb.co/qNWMQKD/Hyperplane.png',
  ' https://i.ibb.co/xgPc6DJ/Imputation-Using-k-NN.png',
  ' https://i.ibb.co/PCZFcFm/Imputation-Using-k-NN.jpg',
  ' https://i.ibb.co/JRgZfyD/Imputing-Missing-Values.png',
  ' https://i.ibb.co/2hcxywL/Initializing-Weights-In-Feedforward-Neural-Networks.png',
  ' https://i.ibb.co/9gwDzkp/Interaction-Term.png',
  ' https://i.ibb.co/1LjW2Hv/Interpolation.jpg',
  ' https://i.ibb.co/QjTNxf0/Jacobian-Matrix.png',
  ' https://i.ibb.co/PNP6qgb/K-Nearest-Neighbors-Tips-And-Tricks.png',
  ' https://i.ibb.co/7218XCr/KNN.jpg',
  ' https://i.ibb.co/HpsQhQy/Kernel-PCA.png',
  ' https://i.ibb.co/gdYzsyd/Kernel-Trick.png',
  ' https://i.ibb.co/TbkPmpb/L1-Norm.jpg',
  ' https://i.ibb.co/SXLzLF5/LDA-for-Dimensionality-Reduction.jpg',
  ' https://i.ibb.co/tbK086N/Lazy-KNN.jpg',
  ' https://i.ibb.co/tQqbJL8/Learning-Curve.png',
  ' https://i.ibb.co/Sxh61V7/Leave-One-Out-Cross-Validation.jpg',
  ' https://i.ibb.co/w7NzmJm/Linear-Combination.png',
  ' https://i.ibb.co/mRBg7Nq/Linear-Discriminant-Analysis.jpg',
  ' https://i.ibb.co/4f0GjdQ/Gini-Index.jpg',
  ' https://i.ibb.co/CwZgw4k/Gradient-Descent.png',
  ' https://i.ibb.co/bWBXCqt/Greek-Letters-1.png',
  ' https://i.ibb.co/Qm2pv5X/Greek-Letters-3.png',
  ' https://i.ibb.co/2spQ31H/Hamming-Loss.jpg',
  ' https://i.ibb.co/hX2xx2W/Handling-Imbalanced-Classes-In-Support-Vector-Machines.png',
  ' https://i.ibb.co/W5jgqLX/Handling-Outliers.jpg',
  ' https://i.ibb.co/YBr4C65/Hessian-Matrix.png',
  ' https://i.ibb.co/hBfHLMP/Heteroskedasticity.jpg',
  '  https://i.ibb.co/fdbLtGF/Hidden-Layer.png',
  '  https://i.ibb.co/5hKSbfH/Hinge-Loss.jpg',
  ' https://i.ibb.co/8df9Szg/How-Norm-Penalties-Work.png',
  '  https://i.ibb.co/2hh84j0/How-to-avoid-overfitting.jpg',
  '  https://i.ibb.co/qNWMQKD/Hyperplane.png',
  '  https://i.ibb.co/xgPc6DJ/Imputation-Using-k-NN.png',
  '  https://i.ibb.co/PCZFcFm/Imputation-Using-k-NN.jpg',
  '  https://i.ibb.co/JRgZfyD/Imputing-Missing-Values.png',
  '  https://i.ibb.co/2hcxywL/Initializing-Weights-In-Feedforward-Neural-Networks.png',
  '  https://i.ibb.co/9gwDzkp/Interaction-Term.png',
  '  https://i.ibb.co/1LjW2Hv/Interpolation.jpg',
  '  https://i.ibb.co/QjTNxf0/Jacobian-Matrix.png',
  '  https://i.ibb.co/PNP6qgb/K-Nearest-Neighbors-Tips-And-Tricks.png',
  '  https://i.ibb.co/7218XCr/KNN.jpg',
  '  https://i.ibb.co/HpsQhQy/Kernel-PCA.png',
  '  https://i.ibb.co/gdYzsyd/Kernel-Trick.png',
  '  https://i.ibb.co/TbkPmpb/L1-Norm.jpg',
  '  https://i.ibb.co/SXLzLF5/LDA-for-Dimensionality-Reduction.jpg',
  '  https://i.ibb.co/tbK086N/Lazy-KNN.jpg',
  '  https://i.ibb.co/tQqbJL8/Learning-Curve.png',
  '  https://i.ibb.co/Sxh61V7/Leave-One-Out-Cross-Validation.jpg',
  '  https://i.ibb.co/w7NzmJm/Linear-Combination.png',
  '  https://i.ibb.co/mRBg7Nq/Linear-Discriminant-Analysis.jpg',
  '  https://i.ibb.co/pfsR9yL/Linear-Regression-Problems-and-Solutions.jpg',
  '  https://i.ibb.co/LvhJPYY/Log-Sum-Exp.png',
  '  https://i.ibb.co/FXfXcJx/MSE-vs-MAE.jpg',
  '  https://i.ibb.co/4R0wR2t/Manhattan-Distance.jpg',
  '  https://i.ibb.co/XWQLJpT/Matrices.png',
  '  https://i.ibb.co/h2xWHt8/Matrix-Inverse.png',
  '  https://i.ibb.co/GvVDB99/Max-Norm.png',
  ' https://i.ibb.co/DbBXLCh/Mean-Squared-Error.jpg',
  ' https://i.ibb.co/ftY58v2/Meanshift-Clustering-By-Analogy.png',
  ' https://i.ibb.co/Y2Sr8qq/Min-Max-Scaling.jpg',
  ' https://i.ibb.co/vx731kZ/Min-Max-Scaling.png',
  ' https://i.ibb.co/0Dqb6qD/Missing-At-Random.png',
  ' https://i.ibb.co/1TmRYc9/Missing-Not-At-Random.png',
  ' https://i.ibb.co/pZ6PSgv/Model-Complexity.png',
  ' https://i.ibb.co/KVCJsXQ/Motivation-for-Kernal-PCA.jpg',
  ' https://i.ibb.co/TbTbBPz/Multicolinearity.jpg',
  ' https://i.ibb.co/GvYKKBy/Naive-Bayes-Classifier.jpg',
  ' https://i.ibb.co/bHb8M0Y/Natural-Log.jpg',
  ' https://i.ibb.co/D9q6nct/Non-Parametric-Methods.jpg',
  ' https://i.ibb.co/7Wg9Y9b/Normalization.jpg',
  ' https://i.ibb.co/R9rZPT2/Notation-1.png',
  ' https://i.ibb.co/t4stjJd/Notions-Of-Probability.png',
  ' https://i.ibb.co/3BDRF7V/Odds-and-Log-Odds-in-Logistic-Regression.jpg',
  ' https://i.ibb.co/0YJJqjS/Odds.png',
  ' https://i.ibb.co/jWDNqpW/One-Hot-Encoding.jpg',
  ' https://i.ibb.co/1n5KPnd/Out-Of-Bag-Error.jpg',
  ' https://i.ibb.co/jMh73L8/Outliars.jpg',
  ' https://i.ibb.co/FDN8sV7/Overfit-vs-Underfit.jpg',
  ' https://i.ibb.co/8Xs4JW7/Parameters-vs-Hyperparameters.jpg',
  ' https://i.ibb.co/QnQ30n0/Parametric-Methods.jpg',
  ' https://i.ibb.co/4RJfLjD/Pearsons-Correlation-Coefficient.jpg',
  ' https://i.ibb.co/WP065Ln/Pearsons-Correlation.png',
  ' https://i.ibb.co/JQ81y4q/Perceptron-Learning.png',
  ' https://i.ibb.co/60zDnrd/Polynomial-Regression.jpg',
  ' https://i.ibb.co/R6GBrLv/Power-Rule.png',
  ' https://i.ibb.co/FwNB0fb/Precision-Recall-Trade-off.jpg',
  ' https://i.ibb.co/HtqZ38k/Precision.jpg',
  ' https://i.ibb.co/TbWh5L1/Preprocessing-Test-And-Training-Sets.jpg',
  ' https://i.ibb.co/NLVJzDL/Preprocessing-When-Tests-and-Training.jpg',
  ' https://i.ibb.co/wMDrqcW/Principal-Component-Analysis.jpg',
  ' https://i.ibb.co/9sbDh2N/Principal-Components.png',
  ' https://i.ibb.co/Lgptm4L/Probability-Density-Function.png',
  ' https://i.ibb.co/R7Mm18j/R-Squared.jpg',
  ' https://i.ibb.co/sm7MkK4/RSS.jpg',
  ' https://i.ibb.co/HxTGRCw/Random-Forest-Classification.jpg',
  ' https://i.ibb.co/rF6RMwK/Recall.jpg',
  ' https://i.ibb.co/BG1g01r/Residual-Sum-Of-Squares.jpg',
  ' https://i.ibb.co/DbHKzQD/Ridge-Regression.png',
  ' https://i.ibb.co/n1CpfxC/Saturation.png',
  ' https://i.ibb.co/FmcP0bY/Selecting-of-components-in-PCA.jpg',
  ' https://i.ibb.co/cYnxHpz/Sensitivity.jpg',
  ' https://i.ibb.co/CHs1Hhz/Singular-Value-Decomposition.jpg',
  ' https://i.ibb.co/F3RnkQq/Slack-Variable-In-Soft-Margin-SVM.png',
  ' https://i.ibb.co/X2fWWGk/Softmax-Normalization.jpg',
  ' https://i.ibb.co/z5qMVnG/Sparsity.jpg',
  ' https://i.ibb.co/z42fzX5/Square-Root.png',
  ' https://i.ibb.co/jWsxyFP/Standard-Error.jpg',
  ' https://i.ibb.co/4mXQLbC/Standardization.jpg',
  ' https://i.ibb.co/WtZ0GWS/Stocastic-Gradient-Descent.jpg',
  ' https://i.ibb.co/9ZQb3hX/Stop-Words.png',
  ' https://i.ibb.co/2jQ6x3Y/Strategies-When-You-Have-High-Variance.png',
  ' https://i.ibb.co/wWWPwN4/Supervised-Vs-Unsupervised-Learning.jpg',
  ' https://i.ibb.co/pZ4R6RV/Supervised-Vs-Unsupervised.png',
  ' https://i.ibb.co/TP6v3pn/T-Tests.jpg',
  ' https://i.ibb.co/S5qHh7k/The-Argument-For-Parametric-Models.jpg',
  ' https://i.ibb.co/k8VJpZM/The-Effect-Of-Dropout-On-Hidden-Units.png',
  ' https://i.ibb.co/SrXhztm/The-Effect-Of-Model-Complexity-On-Training-And-Test-Error.png',
  ' https://i.ibb.co/ggmnSCf/The-Perceptron.jpg',
  ' https://i.ibb.co/fqjDHvF/The-Random-In-Random-Forest.jpg',
  ' https://i.ibb.co/bPf2LKC/Therefore-And-Because-Notation.png',
  ' https://i.ibb.co/J5q70v1/Tomek-Links.jpg',
  ' https://i.ibb.co/1ZcpkRp/Threshold-Activation.png',
  ' https://i.ibb.co/7Chyc1Q/Training-Error-Rate-copy.jpg',
  ' https://i.ibb.co/Nn4sNWN/Training-Error-Rate.jpg',
  ' https://i.ibb.co/gdBYBXw/Underflow.png',
  ' https://i.ibb.co/RCCH173/Vanishing-Gradient-Problem.png',
  ' https://i.ibb.co/LCnYRL9/Variance-For-Feature-Selection.jpg',
  ' https://i.ibb.co/8Ykj0zm/Variance-Inflation-Factor.png',
  ' https://i.ibb.co/PWNRdK5/Variance.png',
  ' https://i.ibb.co/yNQhk8Z/What-are-principal-components.jpg',
  ' https://i.ibb.co/7jvLyH1/Youden-039-s-J-Statistic.jpg',
  ' https://i.ibb.co/3k5kdXD/Z-score.jpg',
  ' https://i.ibb.co/ZYzxd0y/Zero-One-Loss.jpg',
  ' https://i.ibb.co/M9HS52K/k-Nearest-Neighbor.jpg',
  ' https://i.ibb.co/PY6tfbC/k-Fold-Cross-Validation.jpg',
  ' https://i.ibb.co/dLHLQHs/k-NN-Neighborhood-Size.png',
  ' https://i.ibb.co/3p0L5GP/tf-idf.jpg',
  ' https://i.ibb.co/7QXJxDs/t-statistic.png',
  ' https://i.ibb.co/7QXJxDs/t-statistic.png',
  ' https://i.ibb.co/7QXJxDs/t-statistic.png',
  ' https://i.ibb.co/7QXJxDs/t-statistic.png',
  ' https://i.ibb.co/7QXJxDs/t-statistic.png',
  ' https://i.ibb.co/7QXJxDs/t-statistic.png'
]

export const Viewpager = function Viewpager() {
  const index = useRef(0)

  const [props, set] = useSprings(pages.length, i => ({
    x: i * window.innerWidth,
    sc: 1,
    display: 'block',
    config: { mass: 1, tension: 170, friction: 20 }
  }))
  const bind = useGesture(({ down, delta: [xDelta], direction: [xDir], distance, cancel }) => {
    if (down && distance > window.innerWidth / 2)
      cancel((index.current = clamp(index.current + (xDir > 0 ? -1 : 1), 0, pages.length - 1)))
    set(i => {
      if (i < index.current - 1 || i > index.current + 1) return { display: 'none' }
      const x = (i - index.current) * window.innerWidth + (down ? xDelta : 0)
      const sc = down ? 1 - distance / window.innerWidth / 2 : 1
      return { x, sc, display: 'block', friction: '1' }
    })
  })
  return props.map(({ x, display, sc }, i) => (
    <animated.div {...bind()} key={i} style={{ display, transform: x.interpolate(x => `translate3d(${x}px,0,0)`) }}>
      <animated.div style={{ transform: sc.interpolate(s => `scale(${s})`), backgroundImage: `url(${pages[i]})` }} />
    </animated.div>
  ))
}

// render(<Viewpager />, document.getElementById('root'))
